services:
  app_validation:
    image: ${IMAGE_VALIDATION}
    container_name: sw-connect-validation
    restart: unless-stopped
    user: "${HOST_UID}:${HOST_GID}"
    env_file:
      - ../shared/.env.validation
    volumes:
      - ../shared/uploads/validation:/opt/sw-connect/shared/uploads/validation
    networks:
      - sw-connect-network

networks:
  sw-connect-network:
    name: sw-connect-network
    external: true
